export const FIATS = [
  { id: "aed", symbol: "AED", name: "United Arab Emirates Dirham" },
  { id: "ars", symbol: "ARS", name: "Argentine Peso" },
  { id: "aud", symbol: "AUD", name: "Australian Dollar" },
  { id: "bdt", symbol: "BDT", name: "Bangladeshi Taka" },
  { id: "bhd", symbol: "BHD", name: "Bahraini Dinar" },
  { id: "bmd", symbol: "BMD", name: "Bermudian Dollar" },
  { id: "brl", symbol: "BRL", name: "Brazilian Real" },
  { id: "cad", symbol: "CAD", name: "Canadian Dollar" },
  { id: "chf", symbol: "CHF", name: "Swiss Franc" },
  { id: "clp", symbol: "CLP", name: "Chilean Peso" },
  { id: "cny", symbol: "CNY", name: "Chinese Yuan" },
  { id: "czk", symbol: "CZK", name: "Czech Koruna" },
  { id: "dkk", symbol: "DKK", name: "Danish Krone" },
  { id: "eur", symbol: "EUR", name: "Euro" },
  { id: "gbp", symbol: "GBP", name: "British Pound Sterling" },
  { id: "gel", symbol: "GEL", name: "Georgian Lari" },
  { id: "hkd", symbol: "HKD", name: "Hong Kong Dollar" },
  { id: "huf", symbol: "HUF", name: "Hungarian Forint" },
  { id: "idr", symbol: "IDR", name: "Indonesian Rupiah" },
  { id: "ils", symbol: "ILS", name: "Israeli New Shekel" },
  { id: "inr", symbol: "INR", name: "Indian Rupee" },
  { id: "jpy", symbol: "JPY", name: "Japanese Yen" },
  { id: "krw", symbol: "KRW", name: "South Korean Won" },
  { id: "kwd", symbol: "KWD", name: "Kuwaiti Dinar" },
  { id: "lkr", symbol: "LKR", name: "Sri Lankan Rupee" },
  { id: "mmk", symbol: "MMK", name: "Myanmar Kyat" },
  { id: "mxn", symbol: "MXN", name: "Mexican Peso" },
  { id: "myr", symbol: "MYR", name: "Malaysian Ringgit" },
  { id: "ngn", symbol: "NGN", name: "Nigerian Naira" },
  { id: "nok", symbol: "NOK", name: "Norwegian Krone" },
  { id: "nzd", symbol: "NZD", name: "New Zealand Dollar" },
  { id: "php", symbol: "PHP", name: "Philippine Peso" },
  { id: "pkr", symbol: "PKR", name: "Pakistani Rupee" },
  { id: "pln", symbol: "PLN", name: "Polish Zloty" },
  { id: "rub", symbol: "RUB", name: "Russian Ruble" },
  { id: "sar", symbol: "SAR", name: "Saudi Riyal" },
  { id: "sek", symbol: "SEK", name: "Swedish Krona" },
  { id: "sgd", symbol: "SGD", name: "Singapore Dollar" },
  { id: "thb", symbol: "THB", name: "Thai Baht" },
  { id: "try", symbol: "TRY", name: "Turkish Lira" },
  { id: "twd", symbol: "TWD", name: "New Taiwan Dollar" },
  { id: "uah", symbol: "UAH", name: "Ukrainian Hryvnia" },
  { id: "usd", symbol: "USD", name: "US Dollar" },
  { id: "vef", symbol: "VEF", name: "Venezuelan Bolívar" },
  { id: "vnd", symbol: "VND", name: "Vietnamese Dong" },
  { id: "zar", symbol: "ZAR", name: "South African Rand" },
  { id: "xag", symbol: "XAG", name: "Silver (troy ounce)" },
  { id: "xau", symbol: "XAU", name: "Gold (troy ounce)" },
  { id: "xdr", symbol: "XDR", name: "Special Drawing Rights" },
];
